name:                ex01
version:             0.1.0.0
github:              "sappho192/haskellexercise"
license:             MIT
author:              "TAE-IN Sappho KIM"
maintainer:          "sappho192@gmail.com"
copyright:           "2020 TAE-IN Sappho KIM"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/TAE-IN Sappho KIM/ex01#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  ex01-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ex01

tests:
  ex01-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ex01
